version: "3.8"
services:
  webapp:
    build: .
    environment:
    - MONGODB_URI
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    ports:
    - "3000:3000"
    command:
    - npm
    - run
    - server-prod
    - --production
    - --port 3000